# Generated by Django 5.1.7 on 2025-03-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supermarket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="products",
            field=models.ManyToManyField(to="supermarket.product"),
        ),
        migrations.DeleteModel(
            name="ProductPurchase",
        ),
    ]
