# Generated by Django 5.1.7 on 2025-03-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supermarket", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Prdocut",
            new_name="Product",
        ),
    ]
